# All-in-One hangfix v1.2
Read-Host 'Please Press Enter to run All-in-One hangfix v1.2'
try {
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Microsoft\Internet Explorer\Main")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\19.0\Browser")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\20.0\Browser")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\DC\Browser")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\19.0\Browser")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\20.0\Browser")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\DC\Browser")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\19.0\AVTracker")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\20.0\AVTracker")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\DC\AVTracker")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\19.0\AVTracker")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\20.0\AVTracker")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\DC\AVTracker")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\19.0\JSPrefs")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\20.0\JSPrefs")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\DC\JSPrefs")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\19.0\JSPrefs")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\20.0\JSPrefs")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\DC\JSPrefs")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\19.0\Originals")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\20.0\Originals")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\DC\Originals")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\19.0\Originals")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\20.0\Originals")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\DC\Originals")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\19.0\Privileged")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\20.0\Privileged")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\DC\Privileged")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\19.0\Privileged")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\20.0\Privileged")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\DC\Privileged")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\19.0\TrustManager")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\20.0\TrustManager")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\DC\TrustManager")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\19.0\TrustManager")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\20.0\TrustManager")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\DC\TrustManager")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\19.0\AVGeneral")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\20.0\AVGeneral")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Acrobat Reader\DC\AVGeneral")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\19.0\AVGeneral")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\20.0\AVGeneral")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Acrobat\DC\AVGeneral")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKCU:\Software\Adobe\Adobe Synchronizer\DC")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\SOFTWARE\Policies\Adobe\Adobe Acrobat\DC\FeatureLockDown")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\SOFTWARE\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\SOFTWARE\WOW6432Node\Policies\Adobe\Adobe Acrobat\DC\FeatureLockDown")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\SOFTWARE\WOW6432Node\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\SOFTWARE\Symitar\SFW\2.0\Logon Options")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\SOFTWARE\WOW6432Node\Symitar\SFW\2.0\Logon Options")){ return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Microsoft\Internet Explorer\Main' -Name 'Isolation' -ea SilentlyContinue) -eq 'PMIL') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Microsoft\Internet Explorer\Main' -Name 'Isolation64Bit' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Microsoft\Internet Explorer\Main' -Name 'TabProcGrowth' -ea SilentlyContinue) -eq 'Medium') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Microsoft\Internet Explorer\Main' -Name 'TabShutdownDelay' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings' -Name 'SyncMode5' -ea SilentlyContinue) -eq 3) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\Browser' -Name 'bGuardProgress' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\Browser' -Name 'bGuardProgress' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\Browser' -Name 'bGuardProgress' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\Browser' -Name 'bGuardProgress' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\Browser' -Name 'bGuardProgress' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\Browser' -Name 'bGuardProgress' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\AVTracker' -Name 'bLoadOnStart' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\AVTracker' -Name 'bLoadOnStart' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\AVTracker' -Name 'bLoadOnStart' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\AVTracker' -Name 'bLoadOnStart' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\AVTracker' -Name 'bLoadOnStart' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\AVTracker' -Name 'bLoadOnStart' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\JSPrefs' -Name 'bConsoleOpen' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\JSPrefs' -Name 'bEnableGlobalSecurity' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\JSPrefs' -Name 'bEnableJS' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\JSPrefs' -Name 'bEnableMenuItems' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\JSPrefs' -Name 'bConsoleOpen' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\JSPrefs' -Name 'bEnableGlobalSecurity' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\JSPrefs' -Name 'bEnableJS' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\JSPrefs' -Name 'bEnableMenuItems' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\JSPrefs' -Name 'bConsoleOpen' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\JSPrefs' -Name 'bEnableGlobalSecurity' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\JSPrefs' -Name 'bEnableJS' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\JSPrefs' -Name 'bEnableMenuItems' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\JSPrefs' -Name 'bConsoleOpen' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\JSPrefs' -Name 'bEnableGlobalSecurity' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\JSPrefs' -Name 'bEnableJS' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\JSPrefs' -Name 'bEnableMenuItems' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\JSPrefs' -Name 'bConsoleOpen' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\JSPrefs' -Name 'bEnableGlobalSecurity' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\JSPrefs' -Name 'bEnableJS' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\JSPrefs' -Name 'bEnableMenuItems' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\JSPrefs' -Name 'bConsoleOpen' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\JSPrefs' -Name 'bEnableGlobalSecurity' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\JSPrefs' -Name 'bEnableJS' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\JSPrefs' -Name 'bEnableMenuItems' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\Originals' -Name 'bAllowByteRangeRequests' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\Originals' -Name 'bDownloadEntireFile' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\Originals' -Name 'bAllowByteRangeRequests' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\Originals' -Name 'bDownloadEntireFile' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\Originals' -Name 'bAllowByteRangeRequests' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\Originals' -Name 'bDownloadEntireFile' -ea SilentlyContinue) -eq 0x00000000 ) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\Originals' -Name 'bAllowByteRangeRequests' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\Originals' -Name 'bDownloadEntireFile' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\Originals' -Name 'bAllowByteRangeRequests' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\Originals' -Name 'bDownloadEntireFile' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\Originals' -Name 'bAllowByteRangeRequests' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\Originals' -Name 'bDownloadEntireFile' -ea SilentlyContinue) -eq 0x00000000 ) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\Privileged' -Name 'bProtectedMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\Privileged' -Name 'bProtectedMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\Privileged' -Name 'bProtectedMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\Privileged' -Name 'bProtectedMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\Privileged' -Name 'bProtectedMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\Privileged' -Name 'bProtectedMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\TrustManager' -Name 'bEnhancedSecurityStandalone' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\TrustManager' -Name 'bEnhancedSecurityInBrowser' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\TrustManager' -Name 'bEnhancedSecurityStandalone' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\TrustManager' -Name 'bEnhancedSecurityInBrowser' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\TrustManager' -Name 'bEnhancedSecurityStandalone' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\TrustManager' -Name 'bEnhancedSecurityInBrowser' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\TrustManager' -Name 'bEnhancedSecurityStandalone' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\TrustManager' -Name 'bEnhancedSecurityInBrowser' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\TrustManager' -Name 'bEnhancedSecurityStandalone' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\TrustManager' -Name 'bEnhancedSecurityInBrowser' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\TrustManager' -Name 'bEnhancedSecurityStandalone' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\TrustManager' -Name 'bEnhancedSecurityInBrowser' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\AVGeneral' -Name 'bBrowserDisplayInReadMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\19.0\AVGeneral' -Name 'iDelayBeforeQuitBrowser' -ea SilentlyContinue) -eq 36864) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\AVGeneral' -Name 'bBrowserDisplayInReadMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\20.0\AVGeneral' -Name 'iDelayBeforeQuitBrowser' -ea SilentlyContinue) -eq 36864) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\AVGeneral' -Name 'bBrowserDisplayInReadMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Acrobat Reader\DC\AVGeneral' -Name 'iDelayBeforeQuitBrowser' -ea SilentlyContinue) -eq 36864) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\AVGeneral' -Name 'bBrowserDisplayInReadMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\19.0\AVGeneral' -Name 'iDelayBeforeQuitBrowser' -ea SilentlyContinue) -eq 36864) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\AVGeneral' -Name 'bBrowserDisplayInReadMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\20.0\AVGeneral' -Name 'iDelayBeforeQuitBrowser' -ea SilentlyContinue) -eq 36864) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\AVGeneral' -Name 'bBrowserDisplayInReadMode' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Acrobat\DC\AVGeneral' -Name 'iDelayBeforeQuitBrowser' -ea SilentlyContinue) -eq 36864) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Synchronizer\DC' -Name 'iDefaultFeedTTL' -ea SilentlyContinue) -eq 2147483647) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Synchronizer\DC' -Name 'iSharedReviewCommentCheck' -ea SilentlyContinue) -eq 2147483647) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Synchronizer\DC' -Name 'iSuspendLength' -ea SilentlyContinue) -eq 2592000) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKCU:\Software\Adobe\Adobe Synchronizer\DC' -Name 'bShowNotification' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Policies\Adobe\Adobe Acrobat\DC\FeatureLockDown' -Name 'bProtectedMode' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Policies\Adobe\Adobe Acrobat\DC\FeatureLockDown' -Name 'bDisallowDLLUnload' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown' -Name 'bProtectedMode' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown' -Name 'bDisallowDLLUnload' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\WOW6432Node\Policies\Adobe\Adobe Acrobat\DC\FeatureLockDown' -Name 'bProtectedMode' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\WOW6432Node\Policies\Adobe\Adobe Acrobat\DC\FeatureLockDown' -Name 'bDisallowDLLUnload' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\WOW6432Node\Policies\Adobe\Adobe Acrobat\DC\FeatureLockDown' -Name 'bEnableProtectedModeAppContainer' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\WOW6432Node\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown' -Name 'bProtectedMode' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\WOW6432Node\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown' -Name 'bDisallowDLLUnload' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\WOW6432Node\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown' -Name 'bEnableProtectedModeAppContainer' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Symitar\SFW\2.0\Logon Options' -Name 'UseStandaloneBrowser' -ea SilentlyContinue) -eq $null) {  } else { return $false };
	if((Get-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\WOW6432Node\Symitar\SFW\2.0\Logon Options' -Name 'UseStandaloneBrowser' -ea SilentlyContinue) -eq $null) {  } else { return $false };
}
catch { return $false }


# ImgCtrApp
Read-Host 'Please Press Enter to run ImgCtrApp'
try {
	if(-NOT (Test-Path -LiteralPath "HKLM:\SOFTWARE\Wow6432Node\ImageCenter")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\SOFTWARE\ImageCenter")){ return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Wow6432Node\ImageCenter' -Name 'WebVirtualPath' -ea SilentlyContinue) -eq 'http://ImgCtrApp/ICWebServices/') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Wow6432Node\ImageCenter' -Name 'SelfUpdateWebVirtualPath' -ea SilentlyContinue) -eq 'http://ImgCtrApp/ICWebServices/') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\ImageCenter' -Name 'WebVirtualPath' -ea SilentlyContinue) -eq 'http://ImgCtrApp/ICWebServices/') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\ImageCenter' -Name 'SelfUpdateWebVirtualPath' -ea SilentlyContinue) -eq 'http://ImgCtrApp/ICWebServices/') {  } else { return $false };
}
catch { return $false }





# OnBase
Read-Host 'Please Press Enter to run Onbase'
try {
	if(-NOT (Test-Path -LiteralPath "HKLM:\SOFTWARE\ODBC\ODBC.INI\Nautilus")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\SOFTWARE\Wow6432Node\ODBC\ODBC.INI\Nautilus")){ return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\ODBC\ODBC.INI\Nautilus' -Name 'Driver' -ea SilentlyContinue) -eq 'C:\WINDOWS\System32\SQLSRV32.dll') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\ODBC\ODBC.INI\Nautilus' -Name 'Server' -ea SilentlyContinue) -eq 'ONBASESRV') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\ODBC\ODBC.INI\Nautilus' -Name 'Database' -ea SilentlyContinue) -eq 'Nautilus') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\ODBC\ODBC.INI\Nautilus' -Name 'LastUser' -ea SilentlyContinue) -eq 'hsi') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Wow6432Node\ODBC\ODBC.INI\Nautilus' -Name 'Driver' -ea SilentlyContinue) -eq 'C:\WINDOWS\System32\SQLSRV32.dll') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Wow6432Node\ODBC\ODBC.INI\Nautilus' -Name 'Server' -ea SilentlyContinue) -eq 'ONBASESRV') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Wow6432Node\ODBC\ODBC.INI\Nautilus' -Name 'Database' -ea SilentlyContinue) -eq 'Nautilus') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Wow6432Node\ODBC\ODBC.INI\Nautilus' -Name 'LastUser' -ea SilentlyContinue) -eq 'hsi') {  } else { return $false };
}
catch { return $false }





# SymitarSettings
Read-Host 'Please Press Enter to run Symitar Settings'
try {
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Browser Options")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Browser Options")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Logon Options")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Logon Options")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Tech Pubs")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Tech Pubs")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SymForm")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SymForm")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\RemoteAdminServer")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\RemoteAdminServer")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Account Manager")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Manager")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Account Selection")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Selection")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\AP")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\AP")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Application Processing")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Application Processing")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\ATM Dialog")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\ATM Dialog")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\General")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\General")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Logon Options")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Logon Options")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\PC Transfer\Text Extensions")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\PC Transfer\Text Extensions")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Shared Branching")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Teller Transactions")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Toolbar Options")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Wire Manager")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Wire Manager")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\Work Report")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Work Report")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Symitar\SFW\2.0\General")){ return $false };
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\General")){ return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Browser Options' -Name 'Startup Page' -ea SilentlyContinue) -eq 'C:\ProgramData\Jack Henry and Associates\Episys For Windows\HTML\Startup.htm') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Browser Options' -Name 'Information Page' -ea SilentlyContinue) -eq 'C:\ProgramData\Jack Henry and Associates\Episys For Windows\Html\Info.htm') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Browser Options' -Name 'Startup Page' -ea SilentlyContinue) -eq 'C:\ProgramData\Jack Henry and Associates\Episys For Windows\HTML\Startup.htm') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Browser Options' -Name 'Information Page' -ea SilentlyContinue) -eq 'C:\ProgramData\Jack Henry and Associates\Episys For Windows\Html\Info.htm') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Logon Options' -Name 'ShowHostName' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Logon Options' -Name 'UserID Flag' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Logon Options' -Name 'Login Name' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Logon Options' -Name 'DefaultHost' -ea SilentlyContinue) -eq 'symitar') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Logon Options' -Name 'ShowHostName' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Logon Options' -Name 'UserID Flag' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Logon Options' -Name 'Login Name' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Logon Options' -Name 'DefaultHost' -ea SilentlyContinue) -eq 'symitar') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Tech Pubs' -Name 'Help File' -ea SilentlyContinue) -eq 'C:\ProgramData\Jack Henry and Associates\Episys For Windows\Documentation\CUDocs\eDocs.chm') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Tech Pubs' -Name 'Help File' -ea SilentlyContinue) -eq 'C:\ProgramData\Jack Henry and Associates\Episys For Windows\Documentation\CUDocs\eDocs.chm') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SymForm' -Name 'Forms Path' -ea SilentlyContinue) -eq 'C:\ProgramData\Jack Henry and Associates\Episys For Windows\Forms') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SymForm' -Name 'Save Path' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SymForm' -Name 'Printers' -ea SilentlyContinue) -eq 'RECEIPT~Star TSP800 (TSP847)~|') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SymForm' -Name 'Focus Color' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SymForm' -Name 'Zoom Percent' -ea SilentlyContinue) -eq '100') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SymForm' -Name 'Forms Path' -ea SilentlyContinue) -eq 'C:\ProgramData\Jack Henry and Associates\Episys For Windows\Forms') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SymForm' -Name 'Save Path' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SymForm' -Name 'Printers' -ea SilentlyContinue) -eq 'RECEIPT~Star TSP800 (TSP847)~|') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SymForm' -Name 'Focus Color' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SymForm' -Name 'Zoom Percent' -ea SilentlyContinue) -eq '100') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Download File Server' -ea SilentlyContinue) -eq 'symitar') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Host Download Institution Number' -ea SilentlyContinue) -eq '000') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Maximum SFW Version Count' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Alternate SFW Network Location' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\RemoteAdminServer' -Name '{66861DFB-4279-423B-8D87-CAE638AC9707}' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\RemoteAdminServer' -Name '{EC28449B-ED3D-4F3C-9973-22F19E67D584}' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Host Download Client Version' -ea SilentlyContinue) -eq 3) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Base Listen Port' -ea SilentlyContinue) -eq '10001') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Max Old Log File Count' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Download File Server' -ea SilentlyContinue) -eq 'symitar') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Host Download Institution Number' -ea SilentlyContinue) -eq '000') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Maximum SFW Version Count' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Alternate SFW Network Location' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\RemoteAdminServer' -Name '{66861DFB-4279-423B-8D87-CAE638AC9707}' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\RemoteAdminServer' -Name '{EC28449B-ED3D-4F3C-9973-22F19E67D584}' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Host Download Client Version' -ea SilentlyContinue) -eq 3) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Base Listen Port' -ea SilentlyContinue) -eq '10001') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\RemoteAdminServer' -Name 'Max Old Log File Count' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Account Manager' -Name 'Tran Hist Items Per Batch' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Account Manager' -Name 'EMailFrom' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Account Manager' -Name 'ShowIQTChart' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Account Manager' -Name 'FMHistory Items Per Batch' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Account Manager' -Name 'BlockEMailFunction' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Account Manager' -Name 'Display Tran History Item Count' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Account Manager' -Name 'Display Record Ordinals' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Account Manager' -Name 'Display Record Locators' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Account Manager' -Name 'Show Ordinals In Options' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Manager' -Name 'Tran Hist Items Per Batch' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Manager' -Name 'EMailFrom' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Manager' -Name 'ShowIQTChart' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Manager' -Name 'FMHistory Items Per Batch' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Manager' -Name 'BlockEMailFunction' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Manager' -Name 'Display Tran History Item Count' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Manager' -Name 'Display Record Ordinals' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Manager' -Name 'Display Record Locators' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Manager' -Name 'Show Ordinals In Options' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Account Selection' -Name 'Items Per Batch' -ea SilentlyContinue) -eq 20) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Account Selection' -Name 'Items Per Batch' -ea SilentlyContinue) -eq 20) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\AP' -Name 'QueuedInvoicesUserList' -ea SilentlyContinue) -eq '0') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\AP' -Name 'StartWithQueue' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\AP' -Name 'QueuedInvoicesUserList' -ea SilentlyContinue) -eq '0') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\AP' -Name 'StartWithQueue' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Application Processing' -Name 'QueuedAppsUserList' -ea SilentlyContinue) -eq '0') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Application Processing' -Name 'StartWithQueue' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Application Processing' -Name 'Show Debt Ratios Chart' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Application Processing' -Name 'Confirm Repeat Step' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Application Processing' -Name 'Initial View' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Application Processing' -Name 'QueuedAppsUserList' -ea SilentlyContinue) -eq '0') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Application Processing' -Name 'StartWithQueue' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Application Processing' -Name 'Show Debt Ratios Chart' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Application Processing' -Name 'Confirm Repeat Step' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Application Processing' -Name 'Initial View' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\ATM Dialog' -Name 'Items Per Batch' -ea SilentlyContinue) -eq 20) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\ATM Dialog' -Name 'Default to Extended View' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\ATM Dialog' -Name 'Search Time Limit' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\ATM Dialog' -Name 'Items Per Batch' -ea SilentlyContinue) -eq 20) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\ATM Dialog' -Name 'Default to Extended View' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\ATM Dialog' -Name 'Search Time Limit' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\General' -Name 'Use Windows Default Printer For Passthrough' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\General' -Name 'Passthrough Printer' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\General' -Name 'Default To User Defined FM Screen' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\General' -Name 'BlinkWarnings' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\General' -Name 'ShowRelatedFunctionsAsButtons' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\General' -Name 'Frequent Related Functions Count' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\General' -Name 'Use Windows Default Printer For Passthrough' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\General' -Name 'Passthrough Printer' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\General' -Name 'Default To User Defined FM Screen' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\General' -Name 'BlinkWarnings' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\General' -Name 'ShowRelatedFunctionsAsButtons' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\General' -Name 'Frequent Related Functions Count' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Logon Options' -Name 'ShowHostName' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Logon Options' -Name 'UserID Flag' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Logon Options' -Name 'Login Name' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Logon Options' -Name 'ShowHostName' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Logon Options' -Name 'UserID Flag' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Logon Options' -Name 'Login Name' -ea SilentlyContinue) -eq '') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\PC Transfer\Text Extensions' -Name 'Text Extensions Space Delimited No Dot' -ea SilentlyContinue) -eq 'css htm html txt') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\PC Transfer\Text Extensions' -Name 'Text Extensions Space Delimited No Dot' -ea SilentlyContinue) -eq 'css htm html txt') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Tran Code List Type' -ea SilentlyContinue) -eq 2) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Shared Branch Function Key Buttons' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Input Area Splitter Height' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Transaction Splitter Width' -ea SilentlyContinue) -eq 320) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Initial View' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 1' -ea SilentlyContinue) -eq 'HELP') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 2' -ea SilentlyContinue) -eq 'CR-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 3' -ea SilentlyContinue) -eq 'KR-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 4' -ea SilentlyContinue) -eq 'CR-KR-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 5' -ea SilentlyContinue) -eq 'SW-CD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 6' -ea SilentlyContinue) -eq 'SW-KD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 7' -ea SilentlyContinue) -eq 'SW-X-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 8' -ea SilentlyContinue) -eq 'LP-X-SW') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 9' -ea SilentlyContinue) -eq 'LP-KR') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 10' -ea SilentlyContinue) -eq 'LA-X-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 11' -ea SilentlyContinue) -eq 'LS') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 12' -ea SilentlyContinue) -eq 'ST') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Tran Code List Type' -ea SilentlyContinue) -eq 2) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Shared Branch Function Key Buttons' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Input Area Splitter Height' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Transaction Splitter Width' -ea SilentlyContinue) -eq 320) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Initial View' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 1' -ea SilentlyContinue) -eq 'HELP') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 2' -ea SilentlyContinue) -eq 'CR-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 3' -ea SilentlyContinue) -eq 'KR-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 4' -ea SilentlyContinue) -eq 'CR-KR-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 5' -ea SilentlyContinue) -eq 'SW-CD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 6' -ea SilentlyContinue) -eq 'SW-KD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 7' -ea SilentlyContinue) -eq 'SW-X-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 8' -ea SilentlyContinue) -eq 'LP-X-SW') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 9' -ea SilentlyContinue) -eq 'LP-KR') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 10' -ea SilentlyContinue) -eq 'LA-X-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 11' -ea SilentlyContinue) -eq 'LS') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Shared Branching' -Name 'Speed Button 12' -ea SilentlyContinue) -eq 'ST') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Teller Transaction Function Key Buttons' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Code Window' -ea SilentlyContinue) -eq 2) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Work Report Max' -ea SilentlyContinue) -eq 200) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Work Report Min' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'InputArea Splitter' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'HistorySplitter' -ea SilentlyContinue) -eq 300) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Recent Count' -ea SilentlyContinue) -eq 4) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Auto Pop' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'DisplayWarningsInDialog' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Display 360 View' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Display Synapsys MRM View' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 1' -ea SilentlyContinue) -eq 'HELP') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 2' -ea SilentlyContinue) -eq 'CR-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 3' -ea SilentlyContinue) -eq 'KR-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 4' -ea SilentlyContinue) -eq 'SW-CD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 5' -ea SilentlyContinue) -eq 'SW-KD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 6' -ea SilentlyContinue) -eq 'SW-X-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 7' -ea SilentlyContinue) -eq 'IQ') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 8' -ea SilentlyContinue) -eq 'ED') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 9' -ea SilentlyContinue) -eq 'CA') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 10' -ea SilentlyContinue) -eq 'LF') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 11' -ea SilentlyContinue) -eq 'RG') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 12' -ea SilentlyContinue) -eq 'VO') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Teller Transaction Function Key Buttons' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Code Window' -ea SilentlyContinue) -eq 2) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Work Report Max' -ea SilentlyContinue) -eq 200) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Work Report Min' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'InputArea Splitter' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'HistorySplitter' -ea SilentlyContinue) -eq 300) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Recent Count' -ea SilentlyContinue) -eq 4) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Auto Pop' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'DisplayWarningsInDialog' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Display 360 View' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Display Synapsys MRM View' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 1' -ea SilentlyContinue) -eq 'HELP') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 2' -ea SilentlyContinue) -eq 'CR-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 3' -ea SilentlyContinue) -eq 'KR-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 4' -ea SilentlyContinue) -eq 'SW-CD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 5' -ea SilentlyContinue) -eq 'SW-KD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 6' -ea SilentlyContinue) -eq 'SW-X-SD') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 7' -ea SilentlyContinue) -eq 'IQ') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 8' -ea SilentlyContinue) -eq 'ED') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 9' -ea SilentlyContinue) -eq 'CA') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 10' -ea SilentlyContinue) -eq 'LF') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 11' -ea SilentlyContinue) -eq 'RG') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Teller Transactions' -Name 'Speed Button 12' -ea SilentlyContinue) -eq 'VO') {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Member Services' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Loan and Member Applications' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Loans' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Collections' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Marketing' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Accounting' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Report Generator' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Administrative' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Information Systems' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Member Business Services' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Account Manager' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Accounts Payable Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'ACH Warehouse' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Application Processing' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'ATM Dialog' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Batch Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Check Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Collateral Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Collection Package' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Console Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Credit Retrieval' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'CTR Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Indirect Lending Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Default Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Device Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'EasyWriter' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'EFT Repeat FM' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Exception Item Manager' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'GL Account Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'GL Posting' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Help File Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Inventory Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Letter File Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'LPT Print Queue Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Member Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Message System' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Parameter Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Participant Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Participation Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Payee Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'PC Transfer' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Report Generator Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Print Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Projections' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Received Item Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Remittance Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Shared Branching' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Teller Totals' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Teller Transactions' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'User Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Wire Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate Transfers' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate Wires' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate Checking' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate Cash Orders' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate User Admin' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate Parameters' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Member Services' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Loan and Member Applications' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Loans' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Collections' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Marketing' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Accounting' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Report Generator' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Administrative' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Information Systems' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Member Business Services' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Account Manager' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Accounts Payable Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'ACH Warehouse' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Application Processing' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'ATM Dialog' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Batch Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Check Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Collateral Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Collection Package' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Console Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Credit Retrieval' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'CTR Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Indirect Lending Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Default Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Device Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'EasyWriter' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'EFT Repeat FM' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Exception Item Manager' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'GL Account Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'GL Posting' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Help File Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Inventory Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Letter File Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'LPT Print Queue Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Member Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Message System' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Parameter Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Participant Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Participation Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Payee Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'PC Transfer' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Report Generator Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Print Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Projections' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Received Item Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Remittance Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Shared Branching' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Teller Totals' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Teller Transactions' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'User Control' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Wire Manager' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate Transfers' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate Wires' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate Checking' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate Cash Orders' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate User Admin' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Toolbar Options' -Name 'Corporate Parameters' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Wire Manager' -Name 'Start with Queue' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Wire Manager' -Name 'Start Queue' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Wire Manager' -Name 'Start with Queue' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Wire Manager' -Name 'Start Queue' -ea SilentlyContinue) -eq 0) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Work Report' -Name 'Max Count' -ea SilentlyContinue) -eq 50) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Work Report' -Name 'Cache Size' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Work Report' -Name 'Cache Grab Size' -ea SilentlyContinue) -eq 10) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\Work Report' -Name 'All Page Cutoff' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Work Report' -Name 'Max Count' -ea SilentlyContinue) -eq 50) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Work Report' -Name 'Cache Size' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Work Report' -Name 'Cache Grab Size' -ea SilentlyContinue) -eq 10) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\Work Report' -Name 'All Page Cutoff' -ea SilentlyContinue) -eq 100) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\General' -Name 'Synapsys Syntegrator Port Number' -ea SilentlyContinue) -eq 10002) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Symitar\SFW\2.0\General' -Name 'Enable Exception Logging' -ea SilentlyContinue) -eq 1) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\General' -Name 'Synapsys Syntegrator Port Number' -ea SilentlyContinue) -eq 10002) {  } else { return $false };
	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Symitar\SFW\2.0\General' -Name 'Enable Exception Logging' -ea SilentlyContinue) -eq 1) {  } else { return $false };
}
catch { return $false }
return $true